services:
  sqs:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        DATABASE_URL: ${DATABASE_URL}
    container_name: ghetto-sqs
    restart: unless-stopped
    environment:
      LOG_LEVEL: ${LOG_LEVEL}
      PORT: ${PORT}
    env_file:
      - .env.dev
    command: >
      bash -c 'npx prisma db push && npm start'
    networks:
      gsqs-host-access:
        aliases:
          - sqs
      mongo-host-access: {}
  
  swagger:
    container_name: ghetto-sqs-swagger
    image: swaggerapi/swagger-ui
    restart: unless-stopped
    ports:
      - '8080:8080'
    volumes:
      - ./openapi/openapi.yaml:/openapi.yaml:ro
    environment:
      SWAGGER_JSON: /openapi.yaml
      DEFAULT_MODEL_RENDERING: model

networks:
  gsqs-host-access:
    name: gsqs-host-access
    driver: bridge
  mongo-host-access:
    external: true
    name: mongo-host-access
